import defaultTheme from "tailwindcss/defaultTheme";
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      backgroundImage: {
        home: "url('../assets/flight-school-name-location-keyword.jpg')",
      },
      fontFamily: {
        sans: ["Noto Sans Lao Variable", ...defaultTheme.fontFamily.sans],
        sans1: ["Merriweather Sans Variable", ...defaultTheme.fontFamily.sans],
        serif: ["Merriweather", ...defaultTheme.fontFamily.serif],
        stock: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
      colors: {
        "primary-50": "#ebf1fa",
        "primary-100": "#ccdbf2",
        "primary-200": "#ccdbf2",
        "primary-300": "#afc7e9",
        "primary-400": "#739cd9",
        "primary-600": "#3269ba",
        "primary-700": "#2e60ab",
        "primary-800": "#2a589b",
        "primary-900": "#264f8c",
        primary: "#3772C9",
        "primary-dark-400": "#1f3d6d",
        "primary-dark-500": "#1a345d",
        "primary-dark-600": "#162c4e",
        "primary-dark-700": "#11233f",
        "primary-dark-800": "#19355d",
        "primary-dark": "#091220",
        secondary: "#0de2de",
        accent: "#f09510",
        "accent-50": "#fdefdb",
        "accent-100": "#f9d6a4",
        "accent-200": "#f7c67f",
        "accent-300": "#f5b65a",
        "accent-400": "#f2a535",
        "accent-700": "#de8a0e",
        muted: "#739cd9",
        "dark-blue": "#09212b",
        "medium-blue": "#2cc0ff",
      },
      height: (theme) => ({
        "screen-1/2": "50vh",
        "screen-2/3": "66vh",
        "screen-1/3": "calc(100vh / 3)",
        "screen-3/4": "75vh",
        "screen-4/5": "80vh",
        "screen-mobile": "92vh", //depends on menu height
      }),
      keyframes: {
        "slow-zoom": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.1)" },
        },
      },
      animation: {
        "slow-zoom": "slow-zoom 30s infinite",
      },
    },
  },
  plugins: [require("@tailwindcss/typography"), require("@tailwindcss/forms")],
  safelist: [
    "[counter-set:_num_var(--num-graduates)]",
    "[counter-set:_num_var(--num-professionals)]",
    "lg:-translate-x-[calc(0*33.33%)]",
    "lg:-translate-x-[calc(1*33.33%)]",
    "lg:-translate-x-[calc(2*33.33%)]",
    "lg:-translate-x-[calc(3*33.33%)]",
    "lg:-translate-x-[calc(4*33.33%)]",
    "lg:-translate-x-[calc(5*33.33%)]",
    "lg:-translate-x-[calc(6*33.33%)]",
    "lg:-translate-x-[calc(7*33.33%)]",
    "lg:-translate-x-[calc(8*33.33%)]",
    "lg:-translate-x-[calc(9*33.33%)]",
    "-translate-x-[calc(0*100%)]",
    "-translate-x-[calc(1*100%)]",
    "-translate-x-[calc(2*100%)]",
    "-translate-x-[calc(3*100%)]",
    "-translate-x-[calc(4*100%)]",
    "-translate-x-[calc(5*100%)]",
    "-translate-x-[calc(6*100%)]",
    "-translate-x-[calc(7*100%)]",
    "-translate-x-[calc(8*100%)]",
    "-translate-x-[calc(9*100%)]",
    "bg-red-700",
    "bg-green-500",
  ],
};
